config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations",
      sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts, only: [:new, :create]
  resources :users, only: [:create, :show] do
    resource :profile, only: [:show]
    resources :posts, only: [:show]
  end
  resources :likes, only: [:create]
  resources :comments, only: [:new, :create]
  resources :chats, only: [:show, :index] do
    resources :chat_messages, only: [:new, :create, :index]
  end

  root "static_pages#home"

  get "all_users" => "users#all_users", as: "all_users"
  get "more_comments/:post_id/:comment_page" => "comments#more_comments"
  get "people" => "users#people", as: "people"

  get "friends/:id" => "users#friends", as: "friends"

  get "timeline/:id" => "users#timeline", as: "timeline"

  post "send_invite/:id" => "invitations#send_invite", as: "send_invite"
  post "decline_invite/:id" => "invitations#decline_invite", as: "decline_invite"
  delete "remove_invite/:id" => "invitations#remove_invite", as: "remove_invite"

  post "make_friend/:friend_id" => "friends_relations#make_friend", as: "make_friend"
  delete "remove_friend/:friend_id" => "friends_relations#destroy", as: "remove_friend"

  delete "like" => "likes#destroy", as: "unlike"

  get "edit" => "profiles#edit", as: "edit_profile"
  put "update_profile" => "profiles#update"

  get '*unmatched_route', to: 'application#not_found'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :require_login, only: :home

  def home
    if user_signed_in?
      @post = Post.new
      @posts = current_user.feed(params[:page])
      @users = take_users
      respond_to do |format|
        format.html { render "home" }
        format.js   { render partial: "shared/pagination" }
      end
    else
      render "welcome"
    end
  end

  def error404
    flash[:danger] = "There is no such page or you have no access to it!"
    redirect_to root_path
  end

   private

  def take_users
    current_user.may_know
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_friend.html.haml
.user-people.clearfix
  = render "users/basic_user_display", user: user, pic_size: "sm"

app/views/static_pages/_functions.html.haml
.functions
  = render 'likes/like', id: object.id, type: object.class.name, likes: object.likes.length, liked: user_liked?(object)
  - object.class.name == "Comment" ? post_id = object.post.id : post_id = object.id
  = render 'comments/make_comment', post_id: post_id
  %p= time_ago_in_words(object.created_at) + " ago"

app/views/static_pages/_header.html.haml
- if user_signed_in?
  #header
    = link_to "odinbook", root_path, id: "logo"
    = link_to "log out", destroy_user_session_path, :method => :delete, class: "logout"
    #left-head
      = link_to people_path, method: :get, id: "people-inv" do
        %span#first-glyph.glyphicon.glyphicon-user{"aria-hidden" => "true"}
        %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
      = link_to chats_path, method: :get, id: "messages" do
        %span.glyphicon.glyphicon-envelope{"aria-hidden" => "true"}
- else
  #unlog-navbar
    %p
      = link_to 'Odinbook', root_path

app/views/static_pages/_odin_sidebar.html.haml
#profile-main
  #wrapper-chunk
    - if user_signed_in?
      #current-user-profile
        #current-user.clearfix
          = render "users/basic_user_display", user: current_user, pic_size: "sm"
        #links.clearfix
          .link
            = link_to "home", root_path
          .link
            = link_to "timeline", timeline_path(current_user.id)
          .link
            = link_to "people", people_path
          .link
            = link_to "friends", friends_path(current_user.id)
          .link
            = link_to "profile", user_profile_path(user_id: current_user.id)
          .link
            = link_to "edit profile", edit_profile_path
          .link
            = link_to "all users", all_users_path
          .link
            = link_to "your chats", chats_path
    - else
      #odin-sidebar
        %p
          %b= link_to "Welcome to Odinbook!", root_path
        %p Fell free to make your own account!
        %p This is a perfect place to waste your time, and do nothing productive!

app/views/static_pages/_profile.html.haml
#main-user-profile
  = render "users/basic_user_display", user: user, pic_size: "vl"
  #friend
    = friend_button(user) if user != current_user && user_signed_in?
#profile-links
  .link
    = link_to "Timeline", timeline_path(user.id)
  .link
    = link_to "Friends", friends_path(user.id)
  .link
    = link_to "About", user_profile_path(user_id: user.id)

app/views/static_pages/_welcome.html.haml
#signing
  #description
    %p
      Odinbook is facebook-like social site! You can have friends and stuff and waste your time! Or not, because we don't have millions of people here :/
    /'= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)'
    = link_to "Sign in", new_user_session_path
    = link_to 'Create your own account!', new_user_registration_path

app/views/static_pages/_you_may_know.html.haml
#you-may-know
  #wrapper-chunk
    %div
      %span Users you may know:
      = render @users

app/views/static_pages/dashboard.html.erb
<div id="main-profile-wrapper">

	<div id="header">
		<p id="logo">facebook</p>
		
		<%= link_to "log out", destroy_user_session_path, :method => :delete %>
	</div>

	<div class="profile">
	</div>

	<div id="post-wrapper">
		<div class="new-post">
			<%= render partial: "posts/form" %>
		</div>
	
		<div class="posts">
			<%= render @posts %>
		</div>
	</div>

	<div id="people">
		<%= render @users %>
	</div>

</div>

app/views/static_pages/friends.html.haml
#main-wrapper
  #wrapper-chunk
    - if @user != current_user && current_user
      #mutual-friends
        %p
          %b Mutual friends:
        = render partial: "static_pages/friend", collection: mutual_friends(@user), locals:{ f_num: 3 }, as: :user
    #friends
      %p
        %b This user friends:
      = render partial: "static_pages/friend", collection: @friends, locals:{ f_num: 3 }, as: :user

app/views/static_pages/home.html.haml
#main-profile-wrapper.clearfix
  #main-wrapper
    #dashboard-posts
      .new-post
        = render "posts/form"
      .posts
        = render @posts
      #inf-scroll
        = will_paginate @posts, page_links: false
  = render "static_pages/you_may_know", users: @users

app/views/static_pages/home.js.haml
$('.posts').append('#{j render @posts}');
- if @posts.next_page
  $('.pagination').replaceWith('#{j will_paginate @posts}');
- else
  $(window).off('scroll');
  $('.pagination').remove();

app/views/static_pages/timeline.html.haml
#main-wrapper.clearfix
  #dashboard-posts
    - if user_signed_in?
      .new-post
        = render partial: "posts/form", locals: { receiver: (@user.id if @user != current_user) }
    .posts
      - if @posts.length > 0
        = render @posts
        = will_paginate @posts
      - else
        %p
          %b This user has no posts!

app/views/static_pages/welcome.html.erb
<%= User.count %>
<%= Post.count %>
<%= render new_user_session_path %>
<%= render new_user_registration_path %> 

app/views/static_pages/welcome.html.haml
#signing
  #description
    %p
      Odinbook is facebook-like social site! You can have friends and stuff and waste your time! Or not, because we don't have millions of people here :/
    /'= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)'
    = link_to "Sign in", new_user_session_path
    = link_to 'Create your own account!', new_user_registration_path