config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations",
      sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts, only: [:new, :create]
  resources :users, only: [:create, :show] do
    resource :profile, only: [:show]
    resources :posts, only: [:show]
  end
  resources :likes, only: [:create]
  resources :comments, only: [:new, :create]
  resources :chats, only: [:show, :index] do
    resources :chat_messages, only: [:new, :create, :index]
  end

  root "static_pages#home"

  get "all_users" => "users#all_users", as: "all_users"
  get "more_comments/:post_id/:comment_page" => "comments#more_comments"
  get "people" => "users#people", as: "people"

  get "friends/:id" => "users#friends", as: "friends"

  get "timeline/:id" => "users#timeline", as: "timeline"

  post "send_invite/:id" => "invitations#send_invite", as: "send_invite"
  post "decline_invite/:id" => "invitations#decline_invite", as: "decline_invite"
  delete "remove_invite/:id" => "invitations#remove_invite", as: "remove_invite"

  post "make_friend/:friend_id" => "friends_relations#make_friend", as: "make_friend"
  delete "remove_friend/:friend_id" => "friends_relations#destroy", as: "remove_friend"

  delete "like" => "likes#destroy", as: "unlike"

  get "edit" => "profiles#edit", as: "edit_profile"
  put "update_profile" => "profiles#update"

  get '*unmatched_route', to: 'application#not_found'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_many :likes, as: :likeable

  belongs_to :post
  belongs_to :author, class_name: "User"

  validates :post_id, presence: true
  validates :content, presence: true


  self.per_page = 6
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:comment)

  def more_comments
    @post = Post.find_by(id: params[:post_id])
    @comments = @post.more_comments(params[:comment_page])
    respond_to do |format|
      format.html { render nothing: true }
      format.js   { render partial: "shared/pagination" }
    end
  end

  def new
    @id = params[:post]
  end

  def create
    @comment = current_user.comments.create(comment_params)
    if @comment.save
      flash[:info] = "comment added"
    else
      flash[:warning] = "adding failed"
    end
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix{:id => "comment-#{comment.id}"}
  .c-main
    .c-core
      .c-content
        = render "users/basic_user_display", user: comment.author, pic_size: "sm"
        %p
          = comment.content
      .c-functions
        = render 'static_pages/functions', object: comment

app/views/comments/_make_comment.html.haml
= link_to new_comment_path(post: post_id), method: :get, id: "make-comment", remote: true  do
  %span.glyphicon.glyphicon-comment{"aria-hidden" => "true"}

app/views/comments/_new.html.haml
= form_for comment, html: { class: "new-comment clearfix" } do |f|
  .form-group
    = f.text_field :content, autofocus: true, placeholder: "...", class: "form-control", required: true
  = f.hidden_field :post_id, { value: @id }
  = f.submit "Send", class: "btn btn-default", style:"float:right"

app/views/comments/new.js.haml
if ($('.new-comment').length)
$('.new-comment').remove();
else
$('#post-#{@id} .p-main').after("#{escape_javascript (render 'comments/new', comment: comment, id: @id)}");