config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations",
      sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts, only: [:new, :create]
  resources :users, only: [:create, :show] do
    resource :profile, only: [:show]
    resources :posts, only: [:show]
  end
  resources :likes, only: [:create]
  resources :comments, only: [:new, :create]
  resources :chats, only: [:show, :index] do
    resources :chat_messages, only: [:new, :create, :index]
  end

  root "static_pages#home"

  get "all_users" => "users#all_users", as: "all_users"
  get "more_comments/:post_id/:comment_page" => "comments#more_comments"
  get "people" => "users#people", as: "people"

  get "friends/:id" => "users#friends", as: "friends"

  get "timeline/:id" => "users#timeline", as: "timeline"

  post "send_invite/:id" => "invitations#send_invite", as: "send_invite"
  post "decline_invite/:id" => "invitations#decline_invite", as: "decline_invite"
  delete "remove_invite/:id" => "invitations#remove_invite", as: "remove_invite"

  post "make_friend/:friend_id" => "friends_relations#make_friend", as: "make_friend"
  delete "remove_friend/:friend_id" => "friends_relations#destroy", as: "remove_friend"

  delete "like" => "likes#destroy", as: "unlike"

  get "edit" => "profiles#edit", as: "edit_profile"
  put "update_profile" => "profiles#update"

  get '*unmatched_route', to: 'application#not_found'
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, class_name: "User"
  belongs_to :likeable, polymorphic: true

  validates_uniqueness_of :liker_id, scope: [:likeable_type, :likeable_id]

  def likes
    likeable.likes.length
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :js
  expose(:like) { current_user.likes_relations.where(likes_params).first_or_create }

  def create
    render 'reload.js', locals: likes_locals(like)
  end

  def destroy
    like.destroy
    render 'reload.js', locals: likes_locals(like)
  end

  private

  def likes_locals(like)
    @id = like.likeable_id
    @type = like.likeable_type
    @likes = like.likes
    { type: @type, id: @id, likes: @likes, liked: user_liked?(like.likeable) }
  end

  def likes_params
    params.require(:liked).permit(:likeable_id, :likeable_type)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
%span.like
  - if liked
    = link_to unlike_path(liked: { likeable_id: id, likeable_type: type } ), method: :delete, id: "like-#{type.downcase}", remote: true do
      %span.glyphicon.glyphicon-thumbs-down{"aria-hidden" => "true"}
    = likes
  - else
    = link_to likes_path(liked: { likeable_id: id, likeable_type: type } ), method: :post, id: "like-#{type.downcase}", remote: true do
      %span.glyphicon.glyphicon-thumbs-up{"aria-hidden" => "true"}
    = likes

app/views/likes/reload.js.haml
$("##{type.downcase}-#{id} span.like").first().replaceWith("#{escape_javascript (render 'likes/like', id: id, type: type, likes: likes, liked: liked )}")