config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations",
      sessions: "sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts, only: [:new, :create]
  resources :users, only: [:create, :show] do
    resource :profile, only: [:show]
    resources :posts, only: [:show]
  end
  resources :likes, only: [:create]
  resources :comments, only: [:new, :create]
  resources :chats, only: [:show, :index] do
    resources :chat_messages, only: [:new, :create, :index]
  end

  root "static_pages#home"

  get "all_users" => "users#all_users", as: "all_users"
  get "more_comments/:post_id/:comment_page" => "comments#more_comments"
  get "people" => "users#people", as: "people"

  get "friends/:id" => "users#friends", as: "friends"

  get "timeline/:id" => "users#timeline", as: "timeline"

  post "send_invite/:id" => "invitations#send_invite", as: "send_invite"
  post "decline_invite/:id" => "invitations#decline_invite", as: "decline_invite"
  delete "remove_invite/:id" => "invitations#remove_invite", as: "remove_invite"

  post "make_friend/:friend_id" => "friends_relations#make_friend", as: "make_friend"
  delete "remove_friend/:friend_id" => "friends_relations#destroy", as: "remove_friend"

  delete "like" => "likes#destroy", as: "unlike"

  get "edit" => "profiles#edit", as: "edit_profile"
  put "update_profile" => "profiles#update"

  get '*unmatched_route', to: 'application#not_found'
end

app/models/user.rb
class User < ActiveRecord::Base
  scope :all_except, ->(user) { where.not(id: user) }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_attached_file :avatar, default_url: "doge.jpg"
  validates_attachment_content_type :avatar, content_type: %r{ \Aimage\/.*\Z }

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 8 }, unless: "password.nil?"
  validates :password, presence: true, if: "id.nil?"

  has_many :posts, foreign_key: "author_id", dependent: :destroy
  has_many :comments, foreign_key: "author_id", dependent: :destroy

  has_many :sent_invitations, class_name: "Invitation", foreign_key: "inviting_user_id", dependent: :destroy
  has_many :received_invitations, class_name: "Invitation", foreign_key: "invited_user_id", dependent: :destroy

  has_many :invited_users, through: :sent_invitations, source: :invited_user
  has_many :invited_by, through: :received_invitations, source: :inviting_user

  has_many :friends_relations, dependent: :destroy
  has_many :friends, through: :friends_relations
  has_many :inverse_friends_relations, class_name: "FriendsRelation", foreign_key: "friend_id", dependent: :destroy
  has_many :inverse_friends, through: :inverse_friends_relations, source: :user

  has_many :likes_relations, class_name: "Like", foreign_key: "liker_id", dependent: :destroy
  has_many :liked_posts, through: :likes_relations, source: :likeable, source_type: "Post"
  has_many :liked_comments, through: :likes_relations, source: :likeable, source_type: "Comment"

  has_one :profile, dependent: :destroy

  has_many :chats, dependent: :destroy
  has_many :inverse_chats, class_name: "Chat", foreign_key: "participant_id", dependent: :destroy

  has_many :chat_messages, foreign_key: "author_id"


  def user_friends
    friends + inverse_friends
  end

  def is_invited_by?(user)
    invited_by.map(&:id).include?(user.id)
  end

  def invited?(user)
    invited_users.map(&:id).include?(user.id)
  end

  def is_friend?(friend)
    user_friends.include?(friend)
  end

  def feed(page = 1)
    ids = user_friends.map(&:id) << id
    Post.where("author_id IN (#{ids.join(',')}) OR receiver_id = :user_id", user_id: id)
        .order(created_at: :desc)
        .paginate(page: page)
        .includes(:author, :likes, :comments)

  end

  def may_know
    ids = user_friends.map(&:id) << id
    User.where("id NOT IN (#{ids.join(',')})")
        .includes(:profile)
        .order("RANDOM()").limit(6)
  end

  def timeline(page = 1)
    Post.where('author_id = :user_id OR receiver_id = :user_id', user_id: id)
        .order(created_at: :desc)
        .paginate(page: page)
        .includes(:author, :likes, :comments)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def public?
    profile.public?
  end

  def accepted_invite(friend_id)
    ids = [id, friend_id].join(',')
    Invitation.find_by("invited_user_id IN (#{ids}) AND
                        inviting_user_id IN (#{ids}) AND status = 'accepted'")
  end

  def current_friend_rel(friend_id)
    ids = [id, friend_id].join(',')
    FriendsRelation.find_by("friend_id IN (#{ids}) OR user_id IN (#{ids})")
  end

  # Omniauth methods / currently unused

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      name = auth.info.name.split(' ')
      user.first_name = name[0]
      user.last_name  = name[1]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
                session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.first_name = data["first_name"] if user.first_name.blank?
        user.last_name  = data["last_name"]  if user.last_name.blank?
      end
    end
  end

  #chats
  def all_chats
    Chat.where("user_id = :id OR participant_id = :id", id: id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_filter :require_login
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      @user.create_profile(private: true)
      sign_in_and_redirect @user
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:timeline, :friends]
  before_action :authorize, only: [:timeline, :friends]

  def all_users
    @users = User.includes(:profile).all_except(current_user)
  end

  def timeline
    if user_signed_in?
      @post = Post.new
    end
    @posts = user.timeline(params[:page])
    respond_to do |format|
      format.html { render "timeline" }
      format.js   { render partial: "shared/pagination" }
    end
  end

  def people
    @sent_invitations = current_user.sent_invitations.where(status: "pending")
      .includes(:invited_user)
    @received_invitations = current_user.received_invitations.where(status: "pending")
      .includes(:inviting_user)
    @friends = current_user.user_friends
  end

  def friends
    @friends = user.user_friends
  end

    private

  def authorize
    user = User.find(params[:id])
    authorization(user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name_link(user)
    link_to user.full_name, timeline_path(user)
  end
end

app/views/users/_basic_user_display.html.haml
%div{:class => "user-pic-#{pic_size}"}
  = image_tag user.avatar.url

.user-name
  = user_name_link(user)
  - if local_assigns[:receiver]
    \&gt; #{user_name_link(receiver)}

app/views/users/_people.html.haml
.user-people.clearfix
  = render "users/basic_user_display", user: user, pic_size: "sm"
  - if f_num != 3
    .message
      = "Add me as afriend!"
  .functions
    - if f_num == 1
      = link_to make_friend_path(user.id), method: :post do
        %span.glyphicon.glyphicon-ok{"aria-hidden" => "true"}
      = link_to decline_invite_path(user.id), method: :post do
        %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
    - elsif f_num == 2
      = link_to remove_invite_path(user.id), method: :delete do
        %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
    - else
      = link_to remove_friend_path(user.id), method: :delete do
        %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}

app/views/users/_user.html.haml
.user.clearfix
  .main
    = render "users/basic_user_display", user: user, pic_size: "md"
    .info
      %p= user.profile.profile_description

app/views/users/all_users.html.haml
#main-wrapper
  #people
    #wrapper-chunk
      #all-users
        - if user_signed_in?
          .user-people.clearfix
            = render "users/basic_user_display", user: current_user, pic_size: "sm"
            .message
              It's me!
          - @users.each do |user|
            .user-people.clearfix
              = render "users/basic_user_display", user: user, pic_size: "sm"
              .message
                = friend_button(user)
        - else
          - @users.each do |user|
            .user-people.clearfix
              = render "users/basic_user_display", user: user, pic_size: "sm"

app/views/users/friends.html.haml
#main-wrapper
  #wrapper-chunk
    - if user != current_user && current_user
      #mutual-friends
        %p
          %b Mutual friends:
        = render partial: "static_pages/friend", collection: mutual_friends(user), locals:{ f_num: 3 }, as: :user
    #friends
      %p
        %b This user friends:
      = render partial: "static_pages/friend", collection: @friends, locals:{ f_num: 3 }, as: :user

app/views/users/people.html.haml
#main-wrapper
  #people
    #wrapper-chunk
      #invites-received
        - if @received_invitations.length > 0
          %p Invites received:
          = render partial: "users/people", collection: @received_invitations.map(&:inviting_user), locals:{ f_num: 1 }, as: :user
        - else
          %b You have not received any invites!
      #invites-sent
        - if @sent_invitations.length > 0
          %p Invites sent:
          = render partial: "users/people", collection: @sent_invitations.map(&:invited_user), locals:{ f_num: 2 }, as: :user
        - else
          %b You have not sent any invites!
      #friends
        - if @friends.length > 0
          %p Your friends:
          = render partial: "users/people", collection: @friends, locals:{ f_num: 3 }, as: :user
        - else
          %b You have no friends hehehehehe xD

app/views/users/show.html.haml
#main-wrapper
  #wrapper-chunk
    .profile-wrapper.clearfix
      = render "basic_user_display", user: user, pic_size: "lg"
      %div
        = link_to "Send friend request", send_invite_path(inv_user_id: user), method: "post"

app/views/users/timeline.html.haml
#main-wrapper.clearfix
  #dashboard-posts
    - if user_signed_in?
      .new-post
        = render partial: "posts/form", locals: { receiver: (user.id if user != current_user) }
      - if @posts.length > 0
        .posts
          = render @posts
          #inf-scroll
            = will_paginate @posts, page_links: false
      - else
        .posts
          %p
            %b This user has no posts!